The Kitchen sink...
It seems no water has been running for a while as theres not a single droplet of water to be seen in the basin...

...
Thats a given since you know your parents rarely remembered to pay their bills.